[build]
  publish = "dist"
  command = "npm run generate"

[context.production]
  command = "BASE_URL=$URL nuxt generate"

[context.deploy-preview]
  command = "BASE_URL=$DEPLOY_PRIME_URL nuxt generate"

[context.branch-deploy]
  command = "BASE_URL=$DEPLOY_URL nuxt generate"
